### ISSUE TITLE
[PATCH] fix spelling, in POD and also function names

### ISSUE THREAD

**Issue by gregoa** [Test-More/Test2#11]
Thanks! I will apply it when I have a chance.

**Comment by exodist** [comment]
Ooops. I accidentally edited instead of replied. Can you provide the link to the patch again?

**Comment by gregoa** [comment]
Heh :)
Sure, the patch is at https://anonscm.debian.org/cgit/pkg-perl/packages/libtest2-perl.git/tree/debian/patches/spelling.patch (or the raw version: https://anonscm.debian.org/cgit/pkg-perl/packages/libtest2-perl.git/plain/debian/patches/spelling.patch )
